OF-2526: Don't include SystemD artifacts in RPM
After new SystemD config files were added (for Debian), the RPM build failed with this error:

```
+ /usr/lib/rpm/check-buildroot
error: Installed (but unpackaged) file(s) found:
   /opt/openfire/dist/etc/ufw/applications.d/openfire
   /opt/openfire/dist/usr/lib/systemd/system/openfire.service
   /opt/openfire/dist/usr/lib/systemd/system/openfire.slice
    Installed (but unpackaged) file(s) found:
   /opt/openfire/dist/etc/ufw/applications.d/openfire
   /opt/openfire/dist/usr/lib/systemd/system/openfire.service
   /opt/openfire/dist/usr/lib/systemd/system/openfire.slice
mv: cannot stat '/home/bamboo-agent3/bamboo-agent-home/xml-data/build-dir/OPENFIRE-NMRB-JOB1/rpmbuild/RPMS/noarch/openfire*rpm': No such file or directory
```

The new files for Debian seem to break the RPM build.

The changes in this commit exclude those files from the RPM build.