Modify the method for determining JRE version
Previously, the method assumed that the format of the JRE version is: major.minor.build.
However, for `openjdk 21`, the value of `System.getProperty("java.version")` is `21`.
This caused the previous method of determination to fail, resulting in the following error message:
> Error: Can not proceed with Openfire Setup.
Your current installation fails to meet minimum server requirements - please see the checklist below:
✗ At least JRE 11
✓ Servlet 2.3 Support
✓ JSP 1.2 Support
✓ Openfire Classes
✓ Openfire Home found (/usr/local/openfire)

Therefore, the method was modified to extract the significant digits using the regular expression `^\d+(\.\d+)?` for version comparison.
The modified method for determination was tested in the following environments:

| JRE Version | 21 | 17.0.1 | 11.0.4 | 10.0.1 | 9.0.1 | 1.8.0_66 |
|---|---|---|---|---|---|---|
| matcher.group(0) | 21 | 17.0 | 11.0 | 10.0 | 9.0 | 1.8 |
| jreVersionCompatible | true | true | true | false | false | false |